Update available-ssid
+ Device name is now a positionnal arguments and is mandatory

- Removed default device name

~ Updated help string
~ Updated function names and parameters
~ Corrected some mistakes

diff --git a/available-ssid b/available-ssid
--- a/available-ssid
+++ b/available-ssid
@@ -1,4 +1,4 @@
-!/bin/bash
+#!/bin/bash
 #
 # This script parses the output of the cli command "iw dev <adapter> scan"
 # to determine all wi-fi networks that can be heard by an Ubuntu client. It
@@ -9,14 +9,15 @@
 # Constans and Global variables parsing Functions                              #
 #------------------------------------------------------------------------------#
 COUNT=1
-HEADERS="False"
 
+# THE DEFAULTS INITIALIZATION - POSITIONALS
+_positionals=()
 # THE DEFAULTS INITIALIZATION - OPTIONALS
-_arg_pretty="off"
 _arg_quiet="off"
-_arg_device="wlan0"
+_arg_pretty="off"
 
 # set our path to 'iw' - enter "which iw" on the CLI if not sure usually "/sbin/iw" or "/usr/sbin/iw"
+DEVICE_NAME=""
 IW=$(which iw)
 
 # List all of our Wi-Fi channels to lookup from the frequency we gather in the output of the "iw" scan command
@@ -77,22 +78,23 @@ function die()
 function begins_with_short_option()
 {
 	local first_option all_short_options
-	all_short_options='pqdh'
+	all_short_options='qph'
 	first_option="${1:0:1}"
 	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
 
+
 # Usage function
 function print_help()
 {
-		echo -e "Help Message"
-    echo -e "Usage: ${0} [-p|--(no-)pretty] [-q|--(no-)quiet] [-d|--device <arg>] [-h|--help]\n"
-		echo -e "Options:"
-		echo -e "\t-d | dev | --device\t: Change the device to be affected by the search"
-		echo -e "\t-h | --help\t\t: Show this help"
-		echo -e "\t-p | --pretty\t\t: Print headers before and after the printing"
-		echo -e "\t-q | --quiet\t\t: Make the execution quiet"
-    echo -e ""
+	echo -e "Help Message"
+    echo -e "Usage: ${0} [-q|--(no-)quiet] [-p|--(no-)pretty] [-h|--help] <device_name>\n"
+	echo -e "Options:"
+	echo -e "\t<device_name>\t\t: Name of the wifi device to scan"
+	echo -e "\t-h | --help\t\t: Show this help"
+	echo -e "\t-p | --pretty\t\t: Print headers before and after the printing"
+	echo -e "\t-q | --quiet\t\t: Make the execution quiet"
+	echo -e ""
 }
 
 parse_commandline ()
@@ -101,18 +103,6 @@ parse_commandline ()
 	do
 		_key="$1"
 		case "$_key" in
-			-p|--no-pretty|--pretty)
-				_arg_pretty="on"
-				test "${1:0:5}" = "--no-" && _arg_pretty="off"
-				;;
-			-p*)
-				_arg_pretty="on"
-				_next="${_key##-p}"
-				if test -n "$_next" -a "$_next" != "$_key"
-				then
-					begins_with_short_option "$_next" && shift && set -- "-p" "-${_next}" "$@" || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
-				fi
-				;;
 			-q|--no-quiet|--quiet)
 				_arg_quiet="on"
 				test "${1:0:5}" = "--no-" && _arg_quiet="off"
@@ -125,16 +115,17 @@ parse_commandline ()
 					begins_with_short_option "$_next" && shift && set -- "-q" "-${_next}" "$@" || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
 				fi
 				;;
-			-d|--device)
-				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
-				_arg_device="$2"
-				shift
+			-p|--no-pretty|--pretty)
+				_arg_pretty="on"
+				test "${1:0:5}" = "--no-" && _arg_pretty="off"
 				;;
-			--device=*)
-				_arg_device="${_key##--device=}"
-				;;
-			-d*)
-				_arg_device="${_key##-d}"
+			-p*)
+				_arg_pretty="on"
+				_next="${_key##-p}"
+				if test -n "$_next" -a "$_next" != "$_key"
+				then
+					begins_with_short_option "$_next" && shift && set -- "-p" "-${_next}" "$@" || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+				fi
 				;;
 			-h|--help)
 				print_help
@@ -145,10 +136,28 @@ parse_commandline ()
 				exit 0
 				;;
 			*)
-				_PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
+				_positionals+=("$1")
 				;;
 		esac
 		shift
+	done
+}
+
+
+handle_passed_args_count ()
+{
+	_required_args_string="'device_name'"
+	test ${#_positionals[@]} -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 1 (namely: $_required_args_string), but got only ${#_positionals[@]}." 1
+	test ${#_positionals[@]} -le 1 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 1 (namely: $_required_args_string), but got ${#_positionals[@]} (the last one was: '${_positionals[*]: -1}')." 1
+}
+
+assign_positional_args ()
+{
+	_positional_names=('_arg_device_name' )
+
+	for (( ii = 0; ii < ${#_positionals[@]}; ii++))
+	do
+		eval "${_positional_names[ii]}=\${_positionals[ii]}" || die "Error during argument parsing, possibly an Argbash bug." 1
 	done
 }
 
@@ -163,27 +172,25 @@ function quiet_echo()
 	fi
 }
 
-function check_interface()
+function check_interface() # <device_name>
 {
 	# Checking that the interface is on
-	if ! { ip link show dev "${_arg_device}" | grep "state UP"; } >/dev/null 2>&1; then
+	if ! { ip link show dev "$1" | grep "state UP"; } >/dev/null 2>&1; then
 		# we reload the wifi and everything
-		quiet_echo -e "${_arg_device} was down. Reactivating it."
-		ip addr flush dev "${_arg_device}"
-		ip link set dev "${_arg_device}" up
-		dhcpcd  -n "$_arg_device" >/dev/null 2>&1 # reload configuration and rebind the interface
-		quiet_echo -e "${_arg_device} is now up."
+		quiet_echo -e "$1 is down. Please reactivate it first"
+		exit 1
 	fi
 }
 
-function print_result()
+function scan_available_networks()  # <device_name>
 {
+	_DEVICE=$1
 	# Set IFS to ensure grep output split only at line end on for statement
 	IFS='
 	'
 	# capture grep output in "iw" scan command in to array
-	quiet_echo "Scanning device ${_arg_device} ..."
-	IW_COMMAND=( `sudo $IW dev $_arg_device scan | grep -o 'BSS ..\:..\:..:..\:..\:..\|SSID: .*\|signal\: .* \|freq\: .*'` )
+	quiet_echo "Scanning networks available for ${_DEVICE} ..."
+	IW_COMMAND=( `sudo $IW dev $_DEVICE scan | grep -o 'BSS ..\:..\:..:..\:..\:..\|SSID: .*\|signal\: .* \|freq\: .*'` )
 
 	# print headers (unless csv output required)
 	if [[ "$_arg_pretty" == "on" ]]
@@ -261,17 +268,21 @@ function print_result()
 	    echo "==============================================================="
 	    echo
 	fi
+
+	unset _DEVICE
 }
-
-
-
-
 
 #------------------------------------------------------------------------------#
 # Main body                                                                    #
 #------------------------------------------------------------------------------#
 
+# Parsing the commands
 parse_commandline "$@"
-check_interface
-print_result
+handle_passed_args_count
+assign_positional_args
+
+DEVICE_NAME=${_positionals[0]}
+
+check_interface $DEVICE_NAME
+scan_available_networks $DEVICE_NAME
 quiet_echo "Done"
