[Feature] Add possibility to search only for a specific ssid
The commit introduces the search for a specific SSID

+ Add search option

~ Change where pretty takes effect
~ Change return codes
~ Change help string
~ Change die function can now interpret string litterals

diff --git a/scan-ssid b/scan-ssid
--- a/scan-ssid
+++ b/scan-ssid
@@ -8,7 +8,6 @@
 #------------------------------------------------------------------------------#
 # Constants and Global variables parsing Functions                             #
 #------------------------------------------------------------------------------#
-COUNT=1
 
 # THE DEFAULTS INITIALIZATION - POSITIONALS
 _positionals=()
@@ -65,13 +64,24 @@ declare -A CHANNELS=(
 #------------------------------------------------------------------------------#
 # Command parsing Functions                                                    #
 #------------------------------------------------------------------------------#
+# ARG_OPTIONAL_SINGLE([search],[s],[Search for a specific ssid information])
+# ARG_OPTIONAL_BOOLEAN([pretty],[p],[Print headers before and after the printing])
+# ARG_OPTIONAL_BOOLEAN([quiet],[q],[Make the execution quiet])
+# ARG_POSITIONAL_SINGLE([wifi_interface],[Name of the wifi interface to scan],[])
+# ARG_HELP([scan-ssid: a cli tool to scan all available Wi-Fi network])
+# ARGBASH_GO()
+# needed because of Argbash --> m4_ignore([
+### START OF CODE GENERATED BY Argbash v2.8.1 one line above ###
+# Argbash is a bash code generator used to get arguments parsing right.
+# Argbash is FREE SOFTWARE, see https://argbash.io for more info
+# Generated online by https://argbash.io/generate
 
 function die()
 {
 	local _ret=$2
 	test -n "$_ret" || _ret=1
 	test "$_PRINT_HELP" = yes && print_help >&2
-	echo "$1" >&2
+	echo -e "$1" >&2
 	exit ${_ret}
 }
 
@@ -87,33 +97,34 @@ function begins_with_short_option()
 # Usage function
 function print_help()
 {
-	echo -e "Help Message"
-    echo -e "Usage: ${0} [-q|--(no-)quiet] [-p|--(no-)pretty] [-h|--help] <device_name>\n"
-	echo -e "Options:"
-	echo -e "\t<device_name>\t\t: Name of the wifi device to scan"
-	echo -e "\t-h | --help\t\t: Show this help"
-	echo -e "\t-p | --pretty\t\t: Print headers before and after the printing"
-	echo -e "\t-q | --quiet\t\t: Make the execution quiet"
-	echo -e ""
+	printf '%s\n' "scan-ssid: a cli tool to scan available Wi-Fi network"
+	printf 'Usage: %s [-q|--(no-)quiet] [-p|--(no-)pretty] [-h|--help] <device_name>\n\n' "$0"
+
+	printf '%s\n' "Options:"
+	printf '\t%s\t\t%s\n'		"<device_name>"	": Name of the wifi interface to scan"
+	printf '\t%s\t\t%s\n'		"-h | --help"		": Show this help message"
+	printf '\t%s\t\t%s\n'		"-p | --pretty"	": Print headers before and after the printing (ignored if '-s' is specified)"
+	printf '\t%s\t\t%s\n'		"-q | --quiet"	": Make the execution quiet"
+	printf '\t%s\t\t%s\n\n' "-s | --search"	": Search for a specific ssid information"
 }
 
-parse_commandline ()
+parse_commandline()
 {
+	_positionals_count=0
 	while test $# -gt 0
 	do
 		_key="$1"
 		case "$_key" in
-			-q|--no-quiet|--quiet)
-				_arg_quiet="on"
-				test "${1:0:5}" = "--no-" && _arg_quiet="off"
+			-s|--search)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_arg_search="$2"
+				shift
 				;;
-			-q*)
-				_arg_quiet="on"
-				_next="${_key##-q}"
-				if test -n "$_next" -a "$_next" != "$_key"
-				then
-					begins_with_short_option "$_next" && shift && set -- "-q" "-${_next}" "$@" || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
-				fi
+			--search=*)
+				_arg_search="${_key##--search=}"
+				;;
+			-s*)
+				_arg_search="${_key##-s}"
 				;;
 			-p|--no-pretty|--pretty)
 				_arg_pretty="on"
@@ -124,7 +135,19 @@ parse_commandline ()
 				_next="${_key##-p}"
 				if test -n "$_next" -a "$_next" != "$_key"
 				then
-					begins_with_short_option "$_next" && shift && set -- "-p" "-${_next}" "$@" || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+					{ begins_with_short_option "$_next" && shift && set -- "-p" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+				fi
+				;;
+			-q|--no-quiet|--quiet)
+				_arg_quiet="on"
+				test "${1:0:5}" = "--no-" && _arg_quiet="off"
+				;;
+			-q*)
+				_arg_quiet="on"
+				_next="${_key##-q}"
+				if test -n "$_next" -a "$_next" != "$_key"
+				then
+					{ begins_with_short_option "$_next" && shift && set -- "-q" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
 				fi
 				;;
 			-h|--help)
@@ -136,7 +159,9 @@ parse_commandline ()
 				exit 0
 				;;
 			*)
-				_positionals+=("$1")
+				_last_positional="$1"
+				_positionals+=("$_last_positional")
+				_positionals_count=$((_positionals_count + 1))
 				;;
 		esac
 		shift
@@ -144,20 +169,25 @@ parse_commandline ()
 }
 
 
-handle_passed_args_count ()
+handle_passed_args_count()
 {
-	_required_args_string="'device_name'"
-	test ${#_positionals[@]} -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 1 (namely: $_required_args_string), but got only ${#_positionals[@]}." 1
-	test ${#_positionals[@]} -le 1 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 1 (namely: $_required_args_string), but got ${#_positionals[@]} (the last one was: '${_positionals[*]: -1}')." 1
+	local _required_args_string="'wifi_interface'"
+	test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1
+	test "${_positionals_count}" -le 1 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
 }
 
-assign_positional_args ()
-{
-	_positional_names=('_arg_device_name' )
 
-	for (( ii = 0; ii < ${#_positionals[@]}; ii++))
+assign_positional_args()
+{
+	local _positional_name _shift_for=$1
+	_positional_names="_arg_wifi_interface "
+
+	shift $_shift_for
+	for _positional_name in ${_positional_names}
 	do
-		eval "${_positional_names[ii]}=\${_positionals[ii]}" || die "Error during argument parsing, possibly an Argbash bug." 1
+		test $# -gt 0 || break
+		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
+		shift
 	done
 }
 
@@ -167,7 +197,7 @@ assign_positional_args ()
 
 function quiet_echo()
 {
-	if ! [[ "${_arg_quiet}" == "on" ]]; then
+	if [ "${_arg_quiet}" == "off" ]; then
 		echo -e "$@"
 	fi
 }
@@ -175,11 +205,14 @@ function quiet_echo()
 function check_interface() # <device_name>
 {
 	# Checking that the interface is on
-	if ! { ip link show dev "$1" | grep "UP"; } >/dev/null 2>&1; then
+	ip link show dev "$1" | grep "UP"  >/dev/null 2>&1
+	if [ $? -ne 0 ]; then
 		# we reload the wifi and everything
-		quiet_echo -e "Interface $1 is down."
-		quiet_echo -e "Try running the command: \"sudo ip link set dev ${1} up\""
-		exit 1
+		if [ "${_arg_quiet}" == "off" ]; then
+			die "Interface $1 is down.\nTry running the command: \"sudo ip link set dev ${1} up\"" 1
+		else
+			exit 1
+		fi
 	fi
 }
 
@@ -187,28 +220,26 @@ function scan_available_networks()  # <device_name>
 {
 	_DEVICE=$1
 	# Set IFS to ensure grep output split only at line end on for statement
+	local default_IFS=$IFS
 	IFS='
 	'
 	# capture grep output in "iw" scan command in to array
 	quiet_echo "Scanning networks available for ${_DEVICE} ..."
 	IW_COMMAND=( `sudo $IW dev $_DEVICE scan | grep -o 'BSS ..\:..\:..:..\:..\:..\|SSID: .*\|signal\: .* \|freq\: .*'` )
+
+	# Resetting IFS to previous value
+	IFS=$default_IFS
 }
 
-function display_networks_classic()
+function format_networks()
 {
-	# print headers (unless csv output required)
-	if [[ "$_arg_pretty" == "on" ]]
-	then
-	  echo "BSSID              RSSI     CH    Freq    SSID"
-	  echo "                   (dBm)          (Mhz)"
-	  echo "==============================================================="
-	fi
-
+	local COUNT=1
 
 	# Read through grep output from "iw" scan command
 	for line in "${IW_COMMAND[@]}"
 	do
 	  # set IFS to space & tab
+		local default_IFS=$IFS
 	  IFS=" 	"
 
 	  # first field should be BSS
@@ -267,11 +298,7 @@ function display_networks_classic()
 
 	done | sort -k2
 
-	if [[ "$_arg_pretty" == "on" ]]
-	  then
-	    echo "==============================================================="
-	    echo
-	fi
+	# IFS=$default_IFS
 
 	unset _DEVICE
 }
@@ -284,16 +311,41 @@ function display_networks_classic()
 parse_commandline "$@"
 handle_passed_args_count
 assign_positional_args
-
 DEVICE_NAME=${_positionals[0]}
 
 check_interface $DEVICE_NAME
-scan_available_networks $DEVICE_NAME
 
-if [[ ! -z $IW_COMMAND ]]; then
-	display_networks_classic
+# Scan network and check presence of IW_COMMAND
+scan_available_networks $DEVICE_NAME
+test ! -z "$IW_COMMAND" || die "${RED}${BOLD}Error${RESET}: 'iw' command couldn't be found" 127
+
+
+if [ -z $_arg_search ]; then
+	result=$(format_networks)
 else
-	echo "No Network found"
+	result=$(format_networks | grep $_arg_search)
+	if [  -z "${result}" ]; then
+		die "$_arg_search is not available." 1
+	fi
 fi
-	quiet_echo "Done"
-	exit 0
+
+# Echo the result
+if [ "$_arg_pretty" == "on" ]; then
+	echo "BSSID              RSSI     CH    Freq    SSID"
+	echo "                   (dBm)          (Mhz)"
+	echo "==============================================================="
+else
+	echo "BSSID              RSSI     CH    Freq    SSID"
+fi
+
+IFS=$default_IFS
+echo $result
+
+if [ "$_arg_pretty" == "on" ]; then
+		echo "==============================================================="
+		echo
+fi
+
+
+quiet_echo "Done."
+exit 0
